### ISSUE TITLE
Support for RN macOS

### ISSUE THREAD

**Issue by ospfranco** [oblador/react-native-esbuild#1]
hi @oblador ! Thanks a lot for all your OSS contributions, this is yet another great package. I'm trying to integrate this with [Sol](https://github.com/ospfranco/sol), I think tree-shaking could make a big difference in performance, yet I'm facing some issues:

<img width="1618" alt="Screenshot 000532" src="https://user-images.githubusercontent.com/1634213/170710222-e96622c2-288e-4d8a-b707-bf5d27e51b7b.png">

I assume this has something to do with how rn-macos patches the base imports for the macOS platform. Any idea if this is possible to easily fix?

Thanks a lot!

**Comment by oblador** [comment]
Hi, in your custom esbuild config, can you try setting this:
```js
  resolveExtensions: ['.tsx', '.ts', '.jsx', '.js', '.json']
    .concat(ASSET_EXTENSIONS)
    .map((extension) => [
      `.macos${extension}`,
      `.ios${extension}`,
      `.native${extension}`,
      `.react-native${extension}`,
      extension,
    ])
    .flat()
```

Just to verify that this resolution strategy actually fixes it (it did in my testing), then I can maybe think of a way to automatically support this or with a somewhat neater API.

**Comment by ospfranco** [comment]
That worked! awesome! thanks!

**Comment by ospfranco** [comment]
Ah, sorry to say it worked for the dev/debug build, but I just tried to build a release version and got another error:

<img width="891" alt="Screenshot 000534" src="https://user-images.githubusercontent.com/1634213/170920460-4c6b5921-a6bd-43b9-9949-df7c148ae9a5.png">

**Comment by ospfranco** [comment]
I managed to get it working, I will submit a patch in a bit :)

Edit: I manually edited the asset-destination file to contain the `macos` platform, and the app compiled but it is crashing on start. Trying to figure out what is wrong

**Comment by ospfranco** [comment]
On release mode `Platform.select({'macos': '[SOME VALUE]'}` is not working. Weird :)

Any idea what might be wrong, just looking at the source code I cannot find any obvious reason why this doesn't work.

**Comment by ospfranco** [comment]
Logging Platform.OS returns `iOS`, so I guess the resolver is not actually picking up the macOS files, but the iOS ones?

**Comment by oblador** [comment]
I think the way to start (and they way I wrote this lib) is to understand how it works ”normally”. So in the regular `react-native`/`metro` projects there are no macos/windows config afaik, and I couldn’t find much config to that end in your project either. So it would be great if you could point me to the magic in `react-native-macos` that makes it work.

**Comment by oblador** [comment]
I wonder if maybe there is a custom babel config that does custom resolution of certain files from `react-native` to `react-native-macos`.

**Comment by ospfranco** [comment]
yeah, rn-macos is a funny beast... I'm not 100% of the internals, but from my very shallow understanding it kinda monkey patches the rn files? example, it has its own cli.js file that starts metro and so on. But couldn't really tell you more...
