### ISSUE TITLE
Unable to run  [Unexpected token <]

### ISSUE THREAD

**Issue by afkcodes** [oblador/react-native-esbuild#17]
First of all thanks for all the efforts you have put in for this. i was trying to incorporate this but was getting this error have attached the screenshot i have followed the instruction, do let me know if i am doing something wrong.

![WhatsApp Image 2022-08-14 at 5 23 21 PM](https://user-images.githubusercontent.com/17390257/184535631-e898a25c-9b02-4146-96d3-0822fcee7209.jpeg)

**Comment by oblador** [comment]
Looks like it’s trying to parse HTML, do you have a minimal reproduction I could have a look at?

**Comment by afkcodes** [comment]
yes i will push the code, now

**Comment by afkcodes** [comment]
Here: https://github.com/afkcodes/fito

**Comment by oblador** [comment]
Thanks for the reproduction! I managed to find [this issue](https://github.com/evanw/esbuild/issues/2421) that mention that you should set `"jsx": "react-jsx"` in your `tsconfig.json` `compilerOptions`. I tried doing that in your project and now it works well!
