### ISSUE TITLE
[ERROR] [plugin react-native-asset-loader] Could not resolve "../images/bg_data_empty.png"

### ISSUE THREAD

**Issue by luogao** [oblador/react-native-esbuild#20]
I'm using react-native-esbuild v0.3.1  and I met this error when try react-native esbuild-start

<img width="880" alt="image" src="https://user-images.githubusercontent.com/22949684/185891642-45a3a4b8-1185-4429-a0a3-16f0ded85154.png">

here is my start script:
```bash
"start:es": "react-native esbuild-start  --reset-cache --port=8989 --host=127.0.0.1 --projectRoot=/Users/luogao/Documents/work/rn_content_pool_list",
```

and my react-native.config.js
```javascript
const {
  createEsbuildCommands,
  esmCustomMainFieldResolverPlugin,
} = require('react-native-esbuild');

const commands = createEsbuildCommands(({ plugins, ...rest }) => ({
  ...rest,
  plugins: plugins.concat(esmCustomMainFieldResolverPlugin()),
}));


module.exports = {
  commands,
};

```

Any idea to solve this problem?

**Comment by luogao** [comment]
BTW, I follow the doc and add the simple script `react-native esbuild-start` to my package.json, will throw this Error
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/22949684/185892757-a3c347d8-dcc0-4aee-8a4f-7ecb6d5b8bbb.png">

seems like the default options do not work... any idea?

**Comment by oblador** [comment]
Hi, very odd, what versions of react-native and `@react-native-community/cli-*` are you running? Could you set up a minimal reproducible example repo that I can try out? Since I see this is a TS file, can you try using an import instead of a require statement?

**Comment by luogao** [comment]
Hi, I'm using react-native 0.63.2 
@react-native-community/cli-* 
<img width="370" alt="image" src="https://user-images.githubusercontent.com/22949684/186058442-d37aefd9-5249-49a9-9230-9f109df1344d.png">

**Comment by oblador** [comment]
Aha, that’s a very outdated version. This lib supports 0.68 and up,

**Comment by luogao** [comment]
okay I see. But my project fixed version. Thanks anyway!

Great work Btw, I always want to tree shaking when build a bundle. hahhaaa
