### ISSUE TITLE
Enable asynchronous esbuild config enhancement handlers

### ISSUE THREAD

**Issue by alxroyer** [oblador/react-native-esbuild#25]
# Problem

The `createEsbuildCommands()` expects a synchronous handler.

When fed with an asynchronous handler, the esbuild configuration is invalid.

# Motivation

As far as I've understood...

According to the [documentation](https://github.com/oblador/react-native-esbuild#optional-esbuild-settings), the esbuild configuration shall be defined in the 'react-native.config.js' file.

Unless the project defined as ESM (`"type": "module"` in the 'package.json' file), this file is processed as CommonJS by default.

Certain plugins (like [esbuild-plugin-babel](https://github.com/nativew/esbuild-plugin-babel) for instance) are ESM-only, and therefore require asynchronous loading with `await import()`.

# Workaround

I managed to work it around by wrapping the 'react-native-esbuild' entry handler:
```js
// react-native.config.js
for (const _command of module.exports.commands) {
    // Wrap the initial `func` handler in order to ensure loading of ESM modules before.
    const _initialFunc = _command.func;
    _command.func = async (...args) => {
        await _ensureEsmModulesLoaded();  // `await import()` calls in this function.
        return await _initialFunc(...args);
    };
}
```

**Comment by alxroyer** [comment]
See also [esbuild-plugin-babel#7](https://github.com/nativew/esbuild-plugin-babel/issues/7) for the specific case of 'esbuild-plugin-babel'.

**Comment by oblador** [comment]
Use the babel plugin that comes with this project, it's faster than the linked. See docs: https://github.com/oblador/react-native-esbuild#optional-esbuild-settings
