### ISSUE TITLE
Ability to tune the babel config

### ISSUE THREAD

**Issue by alxroyer** [oblador/react-native-esbuild#26]
Is it possible to tune the babel config working 'react-native-esbuild'?

Configurations in 'babel.config.js' don't seem to be taken into account.

**Comment by alxroyer** [comment]
I tried to read through 'react-native-esbuild' code :
In the 'syntax-aware-loader' coming along with 'react-native-esbuild', the babel config seems to be hard-coded.

**Comment by alxroyer** [comment]
Details on my use case:
- Bundling for Android.
- Switched from Metro to esbuild (mainly due to Metro limitations at bundling libraries declared with the `exports` field), use of [react-native-esbuild](https://www.npmjs.com/package/react-native-esbuild) for the purpose.
- Use of [babel-plugin-transform-bigint-to-jsbi](https://www.npmjs.com/package/babel-plugin-transform-bigint-to-jsbi) and [jsbi](https://www.npmjs.com/package/jsbi) to fix [BigInt](https://github.com/tc39/proposal-bigint) remaining bundling errors.
- Use of [esbuild-plugin-babel](https://www.npmjs.com/package/esbuild-plugin-babel) to have the babel config being processed.

Since the [esbuild-plugin-babel](https://github.com/nativew/esbuild-plugin-babel) would need a couple of improvements, but has been archived lately, I wondered whether [react-native-esbuild](https://www.npmjs.com/package/react-native-esbuild) could directly take into account a given babel configuration.

**Comment by oblador** [comment]
You can configure the plugins in any way you like, see the example in the docs: https://github.com/oblador/react-native-esbuild#flow-syntax-errors-such-as-expected-from-but-found-

The way the syntax aware loader works is by detecting flow types and stripping those with a predefined babel config and detecting reanimated and doing full babel transpilation there using the babel.config.js. Doing full babel transpilation for all files would remove pretty much all performance gains, but you are of course free to do that if that isn't your primary goal. 

This package exposes a better/faster babel plugin that you can use: https://github.com/oblador/react-native-esbuild/blob/master/src/plugins/babel.js

**Comment by alxroyer** [comment]
I was not aware of the `babelPlugin()` provided with 'react-native-esbuild'.
I've tested it, and it works like a charm!
Thanks for the info.

**Comment by evelant** [comment]
@alxroyer Could you share your configuration for `babel-plugin-transform-bigint-to-jsbi`? I'm having some trouble getting that to work correctly.

**Comment by alxroyer** [comment]
Hello @evelant, sorry for the late reply.

According to my notes:
- No particular configuration for `babel-plugin-transform-bigint-to-jsbi`, just:
  ```js
  // babel.config.js
  module.exports = {
    // ...
    plugins: [
      // Ensure support for [big integers](https://github.com/tc39/proposal-bigint).
      // Inspired from:
      // - https://www.npmjs.com/package/babel-plugin-transform-bigint-to-jsbi
      //   (from https://www.npmjs.com/package/babel-plugin-transform-bigint then https://babeljs.io/en/repl)
      // - https://www.npmjs.com/package/jsbi
      "babel-plugin-transform-bigint-to-jsbi",
    ],
  };
  ```
- As far as I remember, the hard thing was to avoid `babel-plugin-transform-bigint-to-jsbi` be applied on the 'jsbi/dist/jsbi.mjs' file.
    - Especially due to [esbuild#1634](https://github.com/evanw/esbuild/issues/1634) taking Go-limited regular expression into account.
    - In order to do, I published a [esbuild-plugin-filter-callback](https://www.npmjs.com/package/esbuild-plugin-filter-callback):
      ```js
      // esbuild.config.js
      const esbuildPluginFilterCallback = require("esbuild-plugin-filter-callback");

      // ...

      // Let's rely on Babel to ensure our final JS code is es2015-compatible.
      // Inspired from:
      // - [react-native-esbuild#22](https://github.com/oblador/react-native-esbuild/issues/22#issuecomment-1248213287).
      // - https://www.npmjs.com/package/esbuild-plugin-babel (initially).
      // - Then [react-native-esbuild#26](https://github.com/oblador/react-native-esbuild/issues/26) (reported by ours)
      esbuildConfig.plugins = (
          esbuildConfig.plugins
          // Unload the 'syntax-aware-loader' plugin (from 'react-native-esbuild').
          .filter((plugin) => (plugin.name !== "syntax-aware-loader"))
          // Replace it with the `babelPlugin()` (from 'react-native-esbuild' as well),
          // filtered-out with our 'esbuild-plugin-filter-callback' plugin.
          .concat(esbuildPluginFilterCallback({
              /**
               * @param {esbuild.OnLoadArgs} args
               * @returns {boolean}
               */
              filter: (args) => {
                  // Babel does not support JSON files (see https://github.com/nativew/esbuild-plugin-babel/issues/8#issuecomment-947638498).
                  if (args.path.endsWith(".json")) return false;
                  // Babel fails at transforming 'jsbi.mjs'. Whatever, this script is already es2015-compatible.
                  if (path.basename(args.path) === "jsbi.mjs") return false;

                  // Process all files by default.
                  return true;
              },
              plugin: reactNativeEsbuild.babelPlugin(),
          }))
      );
      ```

Hope that helps.
