### ISSUE TITLE
Is it different from what Microsoft makes?

### ISSUE THREAD

**Issue by ko-devHong** [oblador/react-native-esbuild#32]
Currently, Microsoft also seems to be offering a bundled library through esbuild. Is it the same thing that you are currently developing?

**Comment by oblador** [comment]
Not really, they are just using esbuild to minify which makes it slightly faster, but are still relying on metro and babel for bundling and transpilation.

**Comment by ko-devHong** [comment]
@oblador  In fact, when I looked at their code, it was shown that it was not used for development, but could only be used in production mode. In production mode, it was seen as replacing serializer with esbuild, but isn't this replacing everything? 

Does your module support split import when importing a Lodash library? Solution if you don't apply?

**Comment by ko-devHong** [comment]
@oblador  Can you write about my question ??

**Comment by oblador** [comment]
It supports tree shaking as stated in the readme.
