### ISSUE TITLE
unknown command 'esbuild-start'

### ISSUE THREAD

**Issue by mementomoriCarpediem** [oblador/react-native-esbuild#34]
- when I tried to 'esbuild-start' command.   I get error as shown in below.
<img width="453" alt="스크린샷 2024-02-24 오후 8 49 59" src="https://github.com/oblador/react-native-esbuild/assets/70994795/ff1295fb-4cfd-4e2d-93cc-866ab690a778">

- react.native-config.js
```
const { commands } = require('react-native-esbuild');

module.exports = {
    ...commands,
    dependencies: {
        'react-native-vector-icons': {
            platforms: {
                ios: null,
            },
        },
    },
};
 
```

**Comment by oblador** [comment]
Hi, don’t spread commands, so just remove the `…` and it should work
