### ISSUE TITLE
Error with 'react-native-blob-util'

### ISSUE THREAD

**Issue by mementomoriCarpediem** [oblador/react-native-esbuild#35]
- when I try to bundle my project, I got some error.  is there any way to resolve the problem ?

- Errors thrown in bundling process
<img width="559" alt="스크린샷 2024-02-25 오후 2 08 08" src="https://github.com/oblador/react-native-esbuild/assets/70994795/66113ec0-e4b8-4192-815f-3b1fc44dee1c">

- react-native.config.js
```const { createEsbuildCommands } = require('react-native-esbuild');

const commands = createEsbuildCommands((config) => ({
    ...config,
}));

module.exports = {
    commands,
    dependencies: {
        'react-native-vector-icons': {
            platforms: {
                ios: null,
            },
        },
    },
};
```

Thanks

**Comment by oblador** [comment]
See README https://github.com/oblador/react-native-esbuild?tab=readme-ov-file#flow-syntax-errors-such-as-expected-from-but-found-
